CREATE TABLE message_analysis (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  user_id BIGINT,
                                  user_text VARCHAR(255),
                                  message_arrival_time TIMESTAMP WITHOUT TIME ZONE,
                                  moderation_negative BOOLEAN,
                                  moderation_score INTEGER
);
